const API=window.DOCTOR_WILSON_API;const $=id=>document.getElementById(id);let propietarios=[];
document.addEventListener("DOMContentLoaded",()=>{cargar();$("formPropietario").onsubmit=guardar;$("btnLimpiar").onclick=limpiar;$("btnCancelar").onclick=limpiar;$("btnActualizar").onclick=cargar;$("buscar").oninput=render;$("btnLimpiarFiltro").onclick=()=>{$("buscar").value="";render()}});
async function req(url,opt){const r=await fetch(url,opt);const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.mensaje||"No fue posible completar la operación.");return d}
async function cargar(){try{propietarios=await req(`${API}/propietarios`);render()}catch(e){$("tablaPropietarios").innerHTML=`<tr><td colspan="7" class="error-tabla">${esc(e.message)}</td></tr>`}}
function render(){const q=$("buscar").value.trim().toLowerCase();const a=propietarios.filter(x=>[x.nombre,x.apellido,x.documento,x.telefono,x.correo,x.direccion].join(" ").toLowerCase().includes(q));$("tablaPropietarios").innerHTML=a.length?a.map(x=>`<tr><td>${x.id_propietario}</td><td><strong>${esc(x.nombre+" "+x.apellido)}</strong></td><td>${esc(x.documento)}</td><td>${esc(x.telefono)}</td><td>${esc(x.correo||"-")}</td><td>${esc(x.direccion||"-")}</td><td><div class="acciones"><button class="btn-accion btn-editar" onclick="editar(${x.id_propietario})">✏️</button><button class="btn-accion btn-eliminar" onclick="eliminar(${x.id_propietario})">🗑️</button></div></td></tr>`).join(""):'<tr><td colspan="7" class="vacio">No se encontraron propietarios.</td></tr>'}
async function guardar(e){e.preventDefault();if(!$("nombre").value.trim()||!$("apellido").value.trim()||!$("documento").value.trim()||!$("telefono").value.trim())return mostrar("Nombre, apellido, documento y teléfono son obligatorios.","error");const p={nombre:$("nombre").value.trim(),apellido:$("apellido").value.trim(),documento:$("documento").value.trim(),telefono:$("telefono").value.trim(),correo:$("correo").value.trim()||null,direccion:$("direccion").value.trim()||null};const edit=Boolean($("id_propietario").value);try{const d=await req(edit?`${API}/propietarios/${$("id_propietario").value}`:`${API}/propietarios`,{method:edit?"PUT":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(p)});mostrar(d.mensaje,"exito");limpiar();await cargar()}catch(e){mostrar(e.message,"error")}}
window.editar=id=>{const x=propietarios.find(p=>Number(p.id_propietario)===Number(id));if(!x)return;$("id_propietario").value=x.id_propietario;$("nombre").value=x.nombre||"";$("apellido").value=x.apellido||"";$("documento").value=x.documento||"";$("telefono").value=x.telefono||"";$("correo").value=x.correo||"";$("direccion").value=x.direccion||"";$("titulo-formulario").textContent="Editar propietario";$("btnGuardar").textContent="💾 Guardar cambios";$("btnCancelar").hidden=false;scrollTo({top:0,behavior:"smooth"})};
window.eliminar=async id=>{const x=propietarios.find(p=>Number(p.id_propietario)===Number(id));if(!x||!confirm(`¿Eliminar a ${x.nombre} ${x.apellido}?`))return;try{await req(`${API}/propietarios/${id}`,{method:"DELETE"});await cargar()}catch(e){alert(e.message)}};
function limpiar(){$("formPropietario").reset();$("id_propietario").value="";$("titulo-formulario").textContent="Registrar propietario";$("btnGuardar").textContent="💾 Guardar propietario";$("btnCancelar").hidden=true}
function mostrar(t,tipo){const m=$("mensajeFormulario");m.textContent=t;m.className=`mensaje-formulario ${tipo}`}
function esc(v){return String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]))}
