-- MySQL Script generated by MySQL Workbench
-- Sun Aug 16 16:54:50 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema doctor_wilson
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema doctor_wilson
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `doctor_wilson` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `doctor_wilson` ;

-- -----------------------------------------------------
-- Table `doctor_wilson`.`especies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `doctor_wilson`.`especies` (
  `id_especie` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `descripcion` VARCHAR(150) NULL DEFAULT NULL,
  PRIMARY KEY (`id_especie`),
  UNIQUE INDEX `nombre` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `doctor_wilson`.`propietarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `doctor_wilson`.`propietarios` (
  `id_propietario` INT NOT NULL AUTO_INCREMENT,
  `ombre` VARCHAR(50) NOT NULL,
  `apellido` VARCHAR(50) NOT NULL,
  `documento` VARCHAR(20) NOT NULL,
  `telefono` VARCHAR(20) NOT NULL,
  `correo` VARCHAR(100) NULL DEFAULT NULL,
  `direccion` VARCHAR(150) NULL DEFAULT NULL,
  PRIMARY KEY (`id_propietario`),
  UNIQUE INDEX `documento` (`documento` ASC) VISIBLE,
  UNIQUE INDEX `correo` (`correo` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `doctor_wilson`.`razas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `doctor_wilson`.`razas` (
  `id_raza` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(80) NOT NULL,
  `descripcion` VARCHAR(150) NULL DEFAULT NULL,
  `id_especie` INT NOT NULL,
  PRIMARY KEY (`id_raza`),
  UNIQUE INDEX `nombre` (`nombre` ASC) VISIBLE,
  INDEX `fk_raza_especie` (`id_especie` ASC) VISIBLE,
  CONSTRAINT `fk_raza_especie`
    FOREIGN KEY (`id_especie`)
    REFERENCES `doctor_wilson`.`especies` (`id_especie`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `doctor_wilson`.`mascotas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `doctor_wilson`.`mascotas` (
  `id_mascota` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `sexo` ENUM('Macho', 'Hembra') NOT NULL,
  `fecha_nacimiento` DATE NULL DEFAULT NULL,
  `color` VARCHAR(50) NULL DEFAULT NULL,
  `id_especie` INT NOT NULL,
  `id_raza` INT NULL DEFAULT NULL,
  `id_propietario` INT NOT NULL,
  PRIMARY KEY (`id_mascota`),
  INDEX `fk_mascota_especie` (`id_especie` ASC) VISIBLE,
  INDEX `fk_mascota_raza` (`id_raza` ASC) VISIBLE,
  INDEX `fk_mascota_propietario` (`id_propietario` ASC) VISIBLE,
  CONSTRAINT `fk_mascota_especie`
    FOREIGN KEY (`id_especie`)
    REFERENCES `doctor_wilson`.`especies` (`id_especie`),
  CONSTRAINT `fk_mascota_propietario`
    FOREIGN KEY (`id_propietario`)
    REFERENCES `doctor_wilson`.`propietarios` (`id_propietario`),
  CONSTRAINT `fk_mascota_raza`
    FOREIGN KEY (`id_raza`)
    REFERENCES `doctor_wilson`.`razas` (`id_raza`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `doctor_wilson`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `doctor_wilson`.`roles` (
  `id_rol` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `descripcion` VARCHAR(150) NULL DEFAULT NULL,
  PRIMARY KEY (`id_rol`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `doctor_wilson`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `doctor_wilson`.`usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `apellido` VARCHAR(50) NOT NULL,
  `documento` VARCHAR(20) NOT NULL,
  `correo` VARCHAR(100) NOT NULL,
  `contrasena` VARCHAR(255) NOT NULL,
  `id_rol` INT NOT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `documento` (`documento` ASC) VISIBLE,
  UNIQUE INDEX `correo` (`correo` ASC) VISIBLE,
  INDEX `id_rol` (`id_rol` ASC) VISIBLE,
  CONSTRAINT `usuarios_ibfk_1`
    FOREIGN KEY (`id_rol`)
    REFERENCES `doctor_wilson`.`roles` (`id_rol`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `doctor_wilson`.`citas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `doctor_wilson`.`citas` (
  `id_cita` INT NOT NULL AUTO_INCREMENT,
  `fecha_hora` DATETIME NOT NULL,
  `motivo` VARCHAR(200) NOT NULL,
  `estado` ENUM('Programada', 'Atendida', 'Cancelada') NOT NULL DEFAULT 'Programada',
  `observaciones` VARCHAR(250) NULL DEFAULT NULL,
  `id_mascota` INT NOT NULL,
  `id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_cita`),
  INDEX `fk_cita_mascota` (`id_mascota` ASC) VISIBLE,
  INDEX `fk_cita_usuario` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_cita_mascota`
    FOREIGN KEY (`id_mascota`)
    REFERENCES `doctor_wilson`.`mascotas` (`id_mascota`),
  CONSTRAINT `fk_cita_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `doctor_wilson`.`usuarios` (`id_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `doctor_wilson`.`facturas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `doctor_wilson`.`facturas` (
  `id_factura` INT NOT NULL AUTO_INCREMENT,
  `id_propietario` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `subtotal` DECIMAL(10,2) NOT NULL,
  `impuesto` DECIMAL(10,2) NULL DEFAULT '0.00',
  `total` DECIMAL(10,2) NOT NULL,
  `estado` VARCHAR(20) NULL DEFAULT 'pendiente',
  PRIMARY KEY (`id_factura`),
  INDEX `fk_facturas_propietario` (`id_propietario` ASC) VISIBLE,
  CONSTRAINT `fk_facturas_propietario`
    FOREIGN KEY (`id_propietario`)
    REFERENCES `doctor_wilson`.`propietarios` (`id_propietario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `doctor_wilson`.`detalle_factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `doctor_wilson`.`detalle_factura` (
  `id_detalle` INT NOT NULL AUTO_INCREMENT,
  `id_factura` INT NOT NULL,
  `descripcion` VARCHAR(150) NOT NULL,
  `cantidad` INT NOT NULL,
  `precio_unitario` DECIMAL(10,2) NOT NULL,
  `subtotal` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id_detalle`),
  INDEX `fk_detalle_factura` (`id_factura` ASC) VISIBLE,
  CONSTRAINT `fk_detalle_factura`
    FOREIGN KEY (`id_factura`)
    REFERENCES `doctor_wilson`.`facturas` (`id_factura`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `doctor_wilson`.`historias_clinicas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `doctor_wilson`.`historias_clinicas` (
  `id_historia` INT NOT NULL AUTO_INCREMENT,
  `id_mascota` INT NOT NULL,
  `fecha` DATETIME NOT NULL,
  `antecedentes` TEXT NULL DEFAULT NULL,
  `diagnostico` TEXT NULL DEFAULT NULL,
  `observaciones` TEXT NULL DEFAULT NULL,
  `motivo_consulta` VARCHAR(200) NOT NULL,
  `tratamiento` TEXT NULL DEFAULT NULL,
  `id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_historia`),
  INDEX `fk_historia_mascota` (`id_mascota` ASC) VISIBLE,
  INDEX `fk_historia_usuario` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_historia_mascota`
    FOREIGN KEY (`id_mascota`)
    REFERENCES `doctor_wilson`.`mascotas` (`id_mascota`),
  CONSTRAINT `fk_historia_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `doctor_wilson`.`usuarios` (`id_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `doctor_wilson`.`vacunas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `doctor_wilson`.`vacunas` (
  `id_vacuna` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `descripcion` VARCHAR(255) NULL DEFAULT NULL,
  `dosis` VARCHAR(50) NULL DEFAULT NULL,
  `fabricante` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id_vacuna`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `doctor_wilson`.`vacunaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `doctor_wilson`.`vacunaciones` (
  `id_vacunacion` INT NOT NULL AUTO_INCREMENT,
  `id_mascota` INT NOT NULL,
  `id_vacuna` INT NOT NULL,
  `fecha_aplicacion` DATE NOT NULL,
  `proxima_dosis` DATE NULL DEFAULT NULL,
  `observaciones` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id_vacunacion`),
  INDEX `fk_vacunaciones_mascota` (`id_mascota` ASC) VISIBLE,
  INDEX `fk_vacunaciones_vacuna` (`id_vacuna` ASC) VISIBLE,
  CONSTRAINT `fk_vacunaciones_mascota`
    FOREIGN KEY (`id_mascota`)
    REFERENCES `doctor_wilson`.`mascotas` (`id_mascota`),
  CONSTRAINT `fk_vacunaciones_vacuna`
    FOREIGN KEY (`id_vacuna`)
    REFERENCES `doctor_wilson`.`vacunas` (`id_vacuna`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
